### ISSUE TITLE
Function to estimate the expected (co)variances

### ISSUE THREAD

**Issue by YimenAraya-Ajoy** [squid-group/squidSim#2]
I think it will be nice to have a function that summarizes the expected patterns of variance and covariance at the different levels due to known and unknown sources. As well as the proportion of (co)variance explained by each process. This is something that is implemented in the squidApp

**Comment by joelpick** [comment]
implemented in b7ba826 with the new expected_variance() function. Is this what you had in mind @YimenAraya-Ajoy ?

**Comment by joelpick** [comment]
need to make it work with multivariate
